spring:
  datasource:
    url: jdbc:mysql://81.69.252.112:3306/mind_mingle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    com.enbo.mapper: debug