spring:
  application:
    name: mindmingle
  datasource:
    url: jdbc:mysql://81.69.252.112:3306/cms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

server:
  port: 8236
  servlet:
    context-path: /

miniProgram:
  appId: test
  appSecret: test

logging:
  level:
    com.enbo.mapper: debug