spring:
  application:
    name: mindmingle
  datasource:
    url: ENC(5dE0RbnKVkK7cQzGSRQDBNHLaEWgBndU70NYWuTiPC+a39a2YpOJ70htcQOCspye/r+GHaVe7X6oZxRRaSiqzgcf0HHyQ7wQfzUAEA7Io+QEO7w0nK7b11Z4/USEl0KO9SxSicChfy3KtF+EGnf8x1rJmE6Bi+91y9vgmawB1pANW6qLQl8kJRWc0mDNCszDo3I3pQrlQuZI//cSkhU48w==)
    username: ENC(5C8szEPzwmaLX5tAWHm/O7GpeFkmLcrx0EnOTGShgzistJ0PIlsPKfJZTHzY40Pd)
    password: ENC(UaS3ejqw1tpgCRUHtD6/H4LXwfd4ZCQlgzVu2CNh9Y9mOb0k4X+gNn+iETgBy8pB)
  liquibase:
    enabled: true
    change-log: sql/changelog.yml

server:
  port: 8236
  servlet:
    context-path: /

jwt:
  header: "Authorization"
  tokenPrefix: "Bearer "
  secret: "aizz"
  expireTime: 3600000

miniProgram:
  appId: ENC(vkgI8UIFzeVpzPSROEdLAzQoHDkVzhyTBknaLXDEgvdVCEoqq150TaubWSmV7/SKsGzPcsiN6XSA+i9UbzS/Zw==)
  appSecret: ENC(/6brlrQOjBIpIU7npJrfLit+35e8U3NY/pU3aE4Xlby69n6tyxC+hUZKiNphblPJx1LPj9VDwWbDPowLGPbfm3pjJXbJOA+rNBJs5gYYanI=)

logging:
  level:
    com.aizz.mapper: debug