spring:
  application:
    name: mindmingle
    token:
      header: Authorization
      salt: test
      conflict: false
      clientExpire: 3600
      serverExpire: 36000
      systemExpire: 60
      ignoreUrls:
        - /auth/login
  datasource:
    url: ENC(gOnBcVzjzLko3yhz9V8BtUA6t+1ajQpzFHFg0xKjeDVjs5dPp1brMoOwFRMNFX9E5jjwgwNqTRElYLrGY3BCrMQuYZeEQgADanaJW8677TU5eUH5OWFOsnkpkUvEMZN7pAlxpunrMivQ81G86G59djwXZXnRbETdBmExMnpSODnWxqSzpar+QEW6VO2qUAQTFQ9k9JCO2P/klsRbqrH7Cg==)
    username: ENC(lIUiI3BbrMl3Mc1Phvmo39u0pgh2Dd3ggefVJs9bIYBSL9bsUnP6pO5vz4HyGVbx0TjAJIlbZ7+aNav1/K0dIw==)
    password: ENC(VRTZ+buSj446+Idf75Qtu+Lt65jDABZ7hyZkF0hHYnhw0CQGbqaCpWsjNuEz9Pqq)
  redis:
    host: 81.69.252.112
    port: 6379
    database: 0
  liquibase:
    enabled: true
    change-log: sql/changelog.yml

server:
  port: 8236
  servlet:
    context-path: /

miniProgram:
  appId: ENC(vkgI8UIFzeVpzPSROEdLAzQoHDkVzhyTBknaLXDEgvdVCEoqq150TaubWSmV7/SKsGzPcsiN6XSA+i9UbzS/Zw==)
  appSecret: ENC(/6brlrQOjBIpIU7npJrfLit+35e8U3NY/pU3aE4Xlby69n6tyxC+hUZKiNphblPJx1LPj9VDwWbDPowLGPbfm3pjJXbJOA+rNBJs5gYYanI=)

sign:
  url: ENC(zMdshMqEeWj9K35CePbDnwx/87vz0wHJ24bQmOIjwkN3xoEVpuem6yu1C7GpJuBXRc5H0JYij6VeKTPN2URXg+xXhv4OAX7gK0D7IWucXxRc67LxzQb61uwCeu1mT+B5)
  token: ENC(7cxVW7/8ot4BD2QZU2e54Hp1vAx77LyB1+yizR+OF5VMs1rxGrHCCkCdzhjgnsR52HsHLa2LyB41y0MM0SOAdEwAle9Y2LXvAcAPOm+Q0iMfuTFVtP87ghAFzGmBgscBh8oWhuarVhfG2iCP8Xdd2mKoab1vTTIsBrvQH6RQ9Q0/pMsm1zbqVGrDpjsDoQumXSgPwyvwoM94m0hdsWTPkeNsdg/6irj3po/uigLtjEzFm0ZrGNO86Q+qhDJZaPRzs3fqjvu7Cj1MGbV7plJv76aPWTFmrfhybyT8wOII+r298boy9wHDldWo0Rww3i/+)

logging:
  level:
    com.aizz.mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}